### ISSUE TITLE
Examples are broken

### ISSUE THREAD

**Issue by arokem** [scikit-learn-contrib/forest-confidence-interval#66]
```
chlosyne:examples (master) $python plot_mpg.py 
Traceback (most recent call last):
  File "plot_mpg.py", line 51, in <module>
    mpg_X_test)
  File "/Users/arokem/source/forest-confidence-interval/forestci/forestci.py", line 221, in random_forest_error
    memory_constrained, memory_limit)
  File "/Users/arokem/source/forest-confidence-interval/forestci/forestci.py", line 98, in _core_computation
    return np.sum((np.dot(inbag - 1, pred_centered.T) / n_trees) ** 2, 0)
ValueError: shapes (98,7) and (2000,294) not aligned: 7 (dim 1) != 2000 (dim 0)
chlosyne:examples (master) $python plot_spam.py 
Traceback (most recent call last):
  File "plot_spam.py", line 49, in <module>
    spam_X_test)
  File "/Users/arokem/source/forest-confidence-interval/forestci/forestci.py", line 221, in random_forest_error
    memory_constrained, memory_limit)
  File "/Users/arokem/source/forest-confidence-interval/forestci/forestci.py", line 98, in _core_computation
    return np.sum((np.dot(inbag - 1, pred_centered.T) / n_trees) ** 2, 0)
ValueError: shapes (1000,20) and (500,4000) not aligned: 20 (dim 1) != 500 (dim 0)
```

**Comment by arokem** [comment]
Fixed in #67
